spring:
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:postgresql://localhost:5432/hrmsproject
    username: postgres       
    password: root

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none         
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true
      hibernate.show_sql: false

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: hrmsprojekt
    database: HRMSProject           

logging:
  level:
    org.springframework.data.neo4j: INFO
    org.springframework.jdbc.core: INFO
