server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hrmsproject
    username: postgres   # zmień jeśli masz inne konto
    password: root   # zmień jeśli masz inne hasło
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: hrmsprojekt   # <- takie miałeś na zrzutach
    database: neo4j
